"""enforce active transaction uniqueness

Revision ID: 7193d547b085
Revises: d6ab2879b5f9
Create Date: 2026-08-04 22:07:45.884074
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '7193d547b085'
down_revision: Union[str, Sequence[str], None] = 'd6ab2879b5f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_borrowing_one_active_per_copy', 'borrowings', ['book_copy_id'], unique=True, sqlite_where=sa.text("status IN ('ACTIVE','OVERDUE')"), postgresql_where=sa.text("status IN ('ACTIVE','OVERDUE')"))
    op.create_index('uq_reservation_one_active_per_user_book', 'reservations', ['user_id', 'book_id'], unique=True, sqlite_where=sa.text("status IN ('ACTIVE','READY')"), postgresql_where=sa.text("status IN ('ACTIVE','READY')"))
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_reservation_one_active_per_user_book', table_name='reservations', sqlite_where=sa.text("status IN ('ACTIVE','READY')"), postgresql_where=sa.text("status IN ('ACTIVE','READY')"))
    op.drop_index('uq_borrowing_one_active_per_copy', table_name='borrowings', sqlite_where=sa.text("status IN ('ACTIVE','OVERDUE')"), postgresql_where=sa.text("status IN ('ACTIVE','OVERDUE')"))
    # ### end Alembic commands ###
